(() => {
  const sessions = [
    {id:'CA0001',name:'Ca 1 – Sáng 09/07',topic:'An toàn lao động',topicId:'ATLD-01',exam:'Đề thi cuối khóa',examId:'04',time:'09:00 - 09:45',date:'2024-07-09',students:42,status:'Đang diễn ra',note:'Bắt đầu: 09:00',supervisor:'Nguyễn Văn An'},
    {id:'CA0002',name:'Ca 2 – Chiều 09/07',topic:'Kỹ năng mềm',topicId:'KNM-02',exam:'Đề thi cuối khóa',examId:'05',time:'14:00 - 14:45',date:'2024-07-09',students:45,status:'Sắp diễn ra',note:'Bắt đầu sau 01:45:20',supervisor:'Trần Thị Bình'},
    {id:'CA0003',name:'Ca 3 – Sáng 10/07',topic:'Tin học văn phòng',topicId:'TINHOC-01',exam:'Đề thi cuối khóa',examId:'06',time:'09:00 - 09:45',date:'2024-07-10',students:41,status:'Sắp diễn ra',note:'Bắt đầu sau 20:45:20',supervisor:'Lê Minh Cường'},
    {id:'CA0000',name:'Ca 0 – Ngày 05/07',topic:'An toàn thông tin',topicId:'ATTT-01',exam:'Đề thi cuối khóa',examId:'03',time:'Đã kết thúc',date:'2024-07-05',students:40,status:'Đã kết thúc',note:'Kết thúc: 10:02',supervisor:'Phạm Quang Dũng'},
    {id:'CA0004',name:'Ca 4 – Chiều 10/07',topic:'Tiếng Anh giao tiếp',topicId:'TA-02',exam:'Đề thi cuối khóa',examId:'07',time:'14:00 - 14:45',date:'2024-07-10',students:48,status:'Đã kết thúc',note:'Kết thúc: Hôm qua',supervisor:'Hoàng Thị Lan'},
    {id:'CA0005',name:'Ca 5 – Sáng 11/07',topic:'Nghiệp vụ bán hàng',topicId:'NVBH-01',exam:'Đề thi cuối khóa',examId:'08',time:'Đã hủy',date:'2024-07-11',students:0,status:'Đã hủy',note:'-',supervisor:'Vũ Đức Mạnh'}
  ];
  const $ = (id) => document.getElementById(id), body = $('proctorTableBody'); if (!body) return;
  let page = 1,pageSize = 6;
  const esc = (value) => String(value).replace(/[&<>'"]/g,(char) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const normalize = (value) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();
  const initials = (name) => name.split(/\s+/).slice(-2).map((part) => part[0]).join('').toUpperCase();
  const statusClass = (status) => ({'Đang diễn ra':'running','Sắp diễn ra':'soon','Đã kết thúc':'ended','Đã hủy':'cancelled'}[status]);
  const filtered = () => { const query = normalize($('proctorSearch').value),topic = $('proctorTopic').value,exam = $('proctorExam').value,status = $('proctorStatus').value,date = $('proctorDate').value; return sessions.filter((item) => (!query || normalize(`${item.name} ${item.id}`).includes(query)) && (!topic || item.topic === topic) && (!exam || item.examId === exam) && (!status || item.status === status) && (!date || item.date === date)); };
  const toast = (message) => { const node = $('proctorToast'); node.textContent = message; node.hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => { node.hidden = true; },2200); };
  function render() { const data = filtered(),pages = Math.max(1,Math.ceil(data.length / pageSize)); page = Math.min(page,pages); const rows = data.slice((page - 1) * pageSize,page * pageSize); body.innerHTML = rows.length ? rows.map((item) => { const action = item.status === 'Đang diễn ra' ? ['monitor','Giám sát','primary'] : item.status === 'Đã kết thúc' ? ['result','Xem kết quả','ghost'] : ['detail','Xem chi tiết','ghost']; return `<tr><td><div class="proctor-session"><span class="proctor-session-icon"><i class="fa-regular fa-calendar"></i></span><div><b>${esc(item.name)}</b><small>Mã ca: ${item.id}</small></div></div></td><td><strong>${esc(item.topic)}</strong><small>ID: ${item.topicId}</small></td><td><strong>${esc(item.exam)}</strong><small>Mã đề: ${item.examId}</small></td><td><strong>${esc(item.time)}</strong><small>${item.date.split('-').reverse().join('/')}</small></td><td><strong>${item.students}</strong><small>thí sinh</small></td><td><span class="proctor-status ${statusClass(item.status)}">${item.status}</span><small>${esc(item.note)}</small></td><td><div class="proctor-supervisor"><span class="proctor-avatar">${initials(item.supervisor)}</span><div><strong>${esc(item.supervisor)}</strong><small>Giám thị 1</small></div></div></td><td><div class="proctor-actions"><button class="btn ${action[2]}" data-action="${action[0]}" data-id="${item.id}">${action[0] === 'monitor' ? '<i class="fa-solid fa-display"></i>' : ''}${action[1]}</button><button data-action="more" data-id="${item.id}" aria-label="Thêm thao tác"><i class="fa-solid fa-ellipsis-vertical"></i></button></div></td></tr>`; }).join('') : '<tr><td colspan="8" class="proctor-empty">Không tìm thấy ca thi phù hợp</td></tr>'; const first = data.length ? (page - 1) * pageSize + 1 : 0,last = Math.min(page * pageSize,data.length); $('proctorSummary').textContent = `Hiển thị ${first} - ${last} trong tổng số ${data.length} ca thi`; $('proctorPagination').innerHTML = `<button class="proctor-page-button" data-page="${page - 1}" ${page === 1 ? 'disabled' : ''}><i class="fa-solid fa-chevron-left"></i></button>${Array.from({length:pages},(_,index) => `<button class="proctor-page-button ${index + 1 === page ? 'active' : ''}" data-page="${index + 1}">${index + 1}</button>`).join('')}<button class="proctor-page-button" data-page="${page + 1}" ${page === pages ? 'disabled' : ''}><i class="fa-solid fa-chevron-right"></i></button>`; }
  const topics = [...new Set(sessions.map((item) => item.topic))],exams = [...new Set(sessions.map((item) => item.examId))]; $('proctorTopic').innerHTML += topics.map((item) => `<option>${item}</option>`).join(''); $('proctorExam').innerHTML += exams.map((item) => `<option value="${item}">Mã đề ${item}</option>`).join('');
  ['proctorSearch','proctorTopic','proctorExam','proctorStatus','proctorDate'].forEach((id) => $(id).addEventListener(id === 'proctorSearch' ? 'input' : 'change',() => { page = 1; render(); }));
  $('refreshProctors').addEventListener('click',() => { ['proctorSearch','proctorTopic','proctorExam','proctorStatus','proctorDate'].forEach((id) => { $(id).value = ''; }); page = 1; render(); toast('Đã làm mới danh sách ca thi'); });
  $('proctorPagination').addEventListener('click',(event) => { const button = event.target.closest('[data-page]'); if (!button || button.disabled) return; page = Number(button.dataset.page); render(); }); $('proctorPageSize').addEventListener('change',(event) => { pageSize = Number(event.target.value); page = 1; render(); });
  body.addEventListener('click',(event) => { const button = event.target.closest('[data-action]'); if (!button) return; if (button.dataset.action === 'monitor' || button.dataset.action === 'detail') window.location.href = `chi-tiet-giam-sat-thi.html?id=${button.dataset.id}`; else if (button.dataset.action === 'result') toast('Đã mở kết quả ca thi trong chế độ demo'); else toast('Ca thi có thể sao chép mã hoặc xem lịch sử thay đổi'); });
  $('proctorGuide').addEventListener('click',() => $('proctorGuideDialog').showModal()); document.querySelectorAll('[data-close-proctor-dialog]').forEach((button) => button.addEventListener('click',() => $('proctorGuideDialog').close())); $('proctorGuideDialog').addEventListener('click',(event) => { if (event.target === $('proctorGuideDialog')) $('proctorGuideDialog').close(); });
  console.assert(sessions.length === 6,'Proctor sessions self-check failed'); render();
})();
