(() => {
  const form=document.getElementById('questionForm');if(!form)return;
  const $=id=>document.getElementById(id),list=$('answerList'),type=$('questionType'),params=new URLSearchParams(location.search),editId=params.get('id');
  let questions=window.LMSStore.all('questions',[]),editing=questions.find(item=>String(item.id)===editId),answers=editing?.answers?.map(item=>item.text)||['Nồng độ khí độc trong không khí','Nhiệt độ môi trường','Độ ẩm tương đối trong không khí','Nhiệt độ và chiều sâu của lò'],correct=new Set(editing?.answers?.map((item,index)=>item.correct?index:null).filter(index=>index!==null)||[0]),dirty=false;
  const toast=(message,tone='success')=>{const node=$('bankToast');node.textContent=message;node.dataset.tone=tone;node.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.hidden=true,2300)};
  function renderAnswers(){const multiple=type.value==='Nhiều lựa chọn',essay=type.value==='Tự luận';if(essay){list.innerHTML='<p class="muted">Câu hỏi tự luận không cần phương án; người chấm sẽ đánh giá thủ công.</p>';$('addAnswer').hidden=true;return}$('addAnswer').hidden=false;if(type.value==='Đúng / Sai'&&answers.join('|')!=='Đúng|Sai'){answers=['Đúng','Sai'];correct=new Set([0])}list.innerHTML=answers.map((answer,index)=>`<div class="answer-row"><input type="${multiple?'checkbox':'radio'}" name="correct" value="${index}" ${correct.has(index)?'checked':''} aria-label="Đáp án đúng ${String.fromCharCode(65+index)}"><b>${String.fromCharCode(65+index)}</b><input type="text" value="${answer.replace(/"/g,'&quot;')}" data-answer="${index}" required aria-label="Nội dung phương án ${String.fromCharCode(65+index)}"><button type="button" data-remove-answer="${index}" ${answers.length<=2?'disabled':''} aria-label="Xóa phương án"><i class="fa-regular fa-trash-can"></i></button></div>`).join('')}
  function hydrate(record){if(!record)return;[...form.elements].forEach(control=>{if(!control.name||control.name==='correct'||control.type==='file')return;if(control.type==='checkbox')control.checked=Boolean(record[control.name]);else if(record[control.name]!=null)control.value=record[control.name]});type.value=record.type||type.value;renderAnswers()}
  const collect=status=>{const data=Object.fromEntries(new FormData(form));const selected=new Set([...form.querySelectorAll('[name=correct]:checked')].map(input=>Number(input.value)));return{id:editing?.id||window.LMSStore.nextId('questions'),type:data.type,category:data.category,topic:data.topic,level:data.level,score:Number(data.score)||0,grading:data.grading,tags:data.tags.trim(),content:data.content.trim(),explanation:data.explanation.trim(),active:form.elements.active.checked,status,answers:data.type==='Tự luận'?[]:answers.map((text,index)=>({text:text.trim(),correct:selected.has(index)})),updatedAt:new Date().toISOString(),createdAt:editing?.createdAt||new Date().toISOString()}};
  function validate(){if(!form.reportValidity())return false;if(type.value!=='Tự luận'&&!form.querySelector('[name=correct]:checked')){toast('Vui lòng chọn ít nhất một đáp án đúng.','error');return false}if(type.value!=='Tự luận'&&answers.some(answer=>!answer.trim())){toast('Nội dung phương án không được để trống.','error');return false}const content=form.elements.content.value.trim().toLowerCase(),duplicate=questions.some(item=>String(item.id)!==String(editing?.id)&&item.content?.trim().toLowerCase()===content);if(duplicate){toast('Nội dung câu hỏi đã tồn tại trong ngân hàng.','error');return false}return true}
  function persist(record){const index=questions.findIndex(item=>String(item.id)===String(record.id));if(index>=0)questions[index]=record;else questions.unshift(record);window.LMSStore.write('questions',questions);window.LMSStore.remove('drafts',`question-${record.id}`);editing=record;dirty=false;return record}
  function save(next=false){if(!validate())return;const record=persist(collect('Đang sử dụng'));toast(next?'Đã lưu câu hỏi, có thể nhập câu tiếp theo.':'Đã lưu câu hỏi vào ngân hàng.');if(next){editing=null;form.reset();answers=['Phương án A','Phương án B','Phương án C','Phương án D'];correct=new Set([0]);renderAnswers();history.replaceState(null,'',location.pathname);form.elements.content.focus()}else setTimeout(()=>location.href=`ngan-hang-de-thi.html?tab=questions&saved=${record.id}`,500)}
  function saveDraft(){const record=collect('Bản nháp');if(!record.content&& !record.tags)return toast('Hãy nhập ít nhất nội dung hoặc tag để lưu nháp.','error');persist(record);window.LMSStore.save('drafts',{id:`question-${record.id}`,kind:'question',record});toast('Đã lưu bản nháp câu hỏi.');}
  type.addEventListener('change',()=>{dirty=true;renderAnswers()});list.addEventListener('change',event=>{if(event.target.name==='correct'){if(event.target.type==='radio')correct=new Set([Number(event.target.value)]);else event.target.checked?correct.add(Number(event.target.value)):correct.delete(Number(event.target.value));dirty=true}});list.addEventListener('input',event=>{if(event.target.dataset.answer!==undefined){answers[Number(event.target.dataset.answer)]=event.target.value;dirty=true}});list.addEventListener('click',event=>{const button=event.target.closest('[data-remove-answer]');if(!button||answers.length<=2)return;const index=Number(button.dataset.removeAnswer);answers.splice(index,1);correct=new Set([...correct].filter(value=>value!==index).map(value=>value>index?value-1:value));renderAnswers();dirty=true});$('addAnswer').addEventListener('click',()=>{if(answers.length>=6)return toast('Tối đa 6 phương án.','error');answers.push(`Phương án ${String.fromCharCode(65+answers.length)}`);renderAnswers();dirty=true});form.addEventListener('input',()=>{dirty=true});form.addEventListener('submit',event=>{event.preventDefault();save(false)});$('saveDraft').addEventListener('click',saveDraft);$('saveAndNext').addEventListener('click',()=>save(true));$('cancelQuestion').addEventListener('click',async()=>{if(dirty){const accepted=await window.appDialog({title:'Rời trang soạn câu hỏi?',message:'Các thay đổi chưa lưu sẽ bị mất.',confirmText:'Rời trang',cancelText:'Ở lại'});if(!accepted)return}location.href='ngan-hang-de-thi.html?tab=questions'});if(editing){$('questionFormTitle').textContent='Chỉnh sửa câu hỏi';hydrate(editing)}else renderAnswers();
})();
