import {
  FontAwesomeFreeSolid,
  type FontAwesomeFreeSolidIconName,
} from '@react-native-vector-icons/fontawesome-free-solid';

type PaperIconProps = {
  name: string;
  color?: string;
  size: number;
  direction?: 'rtl' | 'ltr' | null;
  testID?: string;
};

const iconMap: Record<string, FontAwesomeFreeSolidIconName> = {
  'account-outline': 'user',
  'account-tie-outline': 'user-tie',
  account: 'user',
  'alert-circle-outline': 'circle-exclamation',
  'address-card': 'address-card',
  'arrow-trend-up': 'arrow-trend-up',
  'arrow-up': 'arrow-up',
  'arrow-left': 'arrow-left',
  at: 'at',
  award: 'award',
  bell: 'bell',
  book: 'book',
  'book-open': 'book-open',
  'book-open-page-variant-outline': 'book-open',
  'book-open-page-variant': 'book-open',
  'bookmark-outline': 'bookmark',
  bookmark: 'bookmark',
  'bullhorn-outline': 'bullhorn',
  'calendar-outline': 'calendar-days',
  'calendar-range-outline': 'calendar-days',
  'calendar-range': 'calendar-days',
  'calendar-check': 'calendar-check',
  calendar: 'calendar-days',
  'calendar-plus': 'calendar-plus',
  'chart-box-outline': 'chart-column',
  'chart-donut': 'chart-pie',
  'check-circle-outline': 'circle-check',
  'check-circle': 'circle-check',
  check: 'check',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'circle-outline': 'circle',
  'circle-check': 'circle-check',
  'circle-exclamation': 'circle-exclamation',
  'clipboard-check': 'clipboard-check',
  'clipboard-list': 'clipboard-list',
  'clipboard-text-outline': 'clipboard-list',
  'clock-outline': 'clock',
  'close-circle': 'circle-xmark',
  close: 'xmark',
  'cloud-upload-outline': 'cloud-arrow-up',
  'code-tags': 'code',
  code: 'code',
  comments: 'comments',
  crown: 'crown',
  'dots-horizontal': 'ellipsis',
  'dots-vertical': 'ellipsis-vertical',
  'eye-off': 'eye-slash',
  eye: 'eye',
  'file-document-outline': 'file-lines',
  'file-code-outline': 'file-code',
  'file-pen': 'file-pen',
  'file-pdf-box': 'file-pdf',
  'filter-variant': 'filter',
  'folder-zip-outline': 'file-zipper',
  download: 'download',
  'format-list-bulleted': 'list-ul',
  gear: 'gear',
  gift: 'gift',
  'graduation-cap': 'graduation-cap',
  'help-circle-outline': 'circle-question',
  'help-circle': 'circle-question',
  'home-outline': 'house',
  home: 'house',
  'information-outline': 'circle-info',
  lightbulb: 'lightbulb',
  lock: 'lock',
  'lock-outline': 'lock',
  key: 'key',
  magnify: 'magnifying-glass',
  'menu-down': 'chevron-down',
  'message-outline': 'comment',
  'message-search-outline': 'magnifying-glass',
  'message-text-outline': 'comments',
  'message-text': 'comments',
  minus: 'minus',
  medal: 'medal',
  'numeric-1-box-outline': '1',
  'numeric-2-box-outline': '2',
  'numeric-2-circle-outline': '2',
  paperclip: 'paperclip',
  pin: 'thumbtack',
  'play-circle': 'circle-play',
  play: 'play',
  plus: 'plus',
  'people-group': 'people-group',
  presentation: 'chalkboard-user',
  qrcode: 'qrcode',
  'radiobox-marked': 'circle-dot',
  'send-outline': 'paper-plane',
  send: 'paper-plane',
  'content-save-outline': 'floppy-disk',
  'share-variant-outline': 'share-nodes',
  shield: 'shield',
  sliders: 'sliders',
  'sort-calendar-descending': 'sort-down',
  'sort-variant': 'sort',
  target: 'bullseye',
  trophy: 'trophy',
  'thumb-up-outline': 'thumbs-up',
  'thumb-up': 'thumbs-up',
  'view-grid-outline': 'table-cells-large',
  'user-check': 'user-check',
  users: 'users',
  building: 'building',
  school: 'school',
  star: 'star',
  'chart-line': 'chart-line',
  'chart-column': 'chart-column',
  certificate: 'certificate',
  repeat: 'repeat',
  'triangle-exclamation': 'triangle-exclamation',
  video: 'video',
  'account-group': 'user-group',
  'map-marker-outline': 'location-dot',
};

export function renderFontAwesomeIcon({
  name,
  color,
  size,
  direction,
  testID,
}: PaperIconProps) {
  const fontAwesomeName = iconMap[name] ?? 'circle-question';

  return (
    <FontAwesomeFreeSolid
      name={fontAwesomeName}
      color={color}
      size={size}
      testID={testID}
      style={{ transform: [{ scaleX: direction === 'rtl' ? -1 : 1 }] }}
    />
  );
}
